version: "3"

backend:
    container_name: "backen"
    restart: always
    image: docker.pkg.github.com/kevindupeyrat/portfolio-server/portfolio-server-docker-image:test-docker-compose-01
    ports: 8443:8443

frontend:
    container_name: "frontend"
    image: docker.pkg.github.com/kevindupeyrat/portfolio-ui/portfolio-ui-docker-image:test-docker-compose-01
    ports: 4200:4200